In [25]:

import numpy as np

In [26]:
array = np.array([1,2,3]) 
print(array)

[1 2 3]


In [27]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(array2.shape) 

(15,)


In [28]:
a = array2.reshape(3,5) 

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [29]:
print("shape: ",a.shape) 

print("dimension: ",a.ndim)

print("data type: ",a.dtype.name) 

print("size: ",a.size) 
print("type",type(a))  

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type <class 'numpy.ndarray'>


In [30]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

In [31]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(array3.shape)

(3, 4)


In [33]:
zeros= np.zeros((3,4)) 

In [34]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.empty((4,5))

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316],
       [ 2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211],
       [ 5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105],
       [ 7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [37]:
np.arange(10,50,5) 

array([10, 15, 20, 25, 30, 35, 40, 45])

In [38]:
a= np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [39]:

a= np.array([1,2,3])
b= np.array([4,5,6])

print(a+b) #[5 7 9]
print(a-b) #[-3 -3 -3]
print(a**2) #[1 4 9]

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [40]:

a= np.array([1,2,3,4,5,6,7])

In [41]:
liste = [1,2,3,4]

array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [42]:
array = np.array(liste)
print(array)

[1 2 3 4]


In [43]:
liste2 = list(array)
print(liste2)

[1, 2, 3, 4]


In [44]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [45]:
b=a

c=a

b[0]=5 
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [46]:
d = a.copy()

In [47]:
a= np.array([1,2,3,4,5,6,7]) #vector -> dimension 1
print(a)

[1 2 3 4 5 6 7]


In [48]:
print(a[0])

1


In [49]:
print(a[0:4]) 

[1 2 3 4]


In [50]:
reverse_array = a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [51]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [52]:
print(b[1,1])

print(b[:,1])

print(b[1,:])

print(b[1,1:4])

print(b[-1,:])

print(b[:,-1])

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [53]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
a = array.ravel() 
print(a)

[1 2 3 4 5 6 7 8 9]


In [55]:
array2 = a.reshape(3,3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
array_transpose = array2.T 
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [57]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [58]:
array3.resize((2,3)) 
print(array3)

[[1 2 3]
 [4 5 6]]
